export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  INVENTORY_MANAGER = 'INVENTORY_MANAGER',
}

export enum PurchaseStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
}

export enum TenantPlan {
  BASIC = 'BASIC',
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
}

export enum LedgerTransactionType {
  OPENING_BALANCE = 'OPENING_BALANCE',
  PURCHASE = 'PURCHASE',
  PAYMENT = 'PAYMENT',
  ADJUSTMENT = 'ADJUSTMENT',
  REFUND = 'REFUND',
  CREDIT_NOTE = 'CREDIT_NOTE',
  DEBIT_NOTE = 'DEBIT_NOTE',
}

export enum PaymentMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
  UPI = 'UPI',
  CARD = 'CARD',
  OTHER = 'OTHER',
}

export enum LedgerAccountStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum FeatureCode {
  FEATURE_DASHBOARD = 'FEATURE_DASHBOARD',
  FEATURE_PURCHASES = 'FEATURE_PURCHASES',
  FEATURE_PURCHASE_HISTORY = 'FEATURE_PURCHASE_HISTORY',
  FEATURE_VENDORS = 'FEATURE_VENDORS',
  FEATURE_PRODUCTS = 'FEATURE_PRODUCTS',
  FEATURE_INVENTORY = 'FEATURE_INVENTORY',
  FEATURE_LEDGER = 'FEATURE_LEDGER',
  FEATURE_REPORTS = 'FEATURE_REPORTS',
  FEATURE_INVOICE_UPLOAD = 'FEATURE_INVOICE_UPLOAD',
  FEATURE_AI_ASSISTANT = 'FEATURE_AI_ASSISTANT',
}
